### ISSUE TITLE
Is there a way to control unique access to actions?

### ISSUE THREAD

**Issue by parrker** [Vivify-Ideas/laravel-acl#1]
Hi, I am a bit confused about whether this package provides a way to control permission to a specific action on a user basis, not only user groups? For example, I might have 3 groups: guests, moderators and superadmins. I might want to give a single moderator access to users management, but without giving this moderator full admin rights. Is it possible?

**Comment by goranprijic** [comment]
Hi

great to see that someone is already using this package :)

Groups are not intended to replace the roles (guest, moderator, admin). We started recently with developing this package and we didn't yet provided roles. But we will soon.

Let me explain for what needs the groups are created.

If a user has a permission within some group, that means that he can access that group. For example, imagine situation where you want to allow some user or role to access admin panel but only with privileges to manage comments. You will have a permission called `Manage comments` within group `Administrator privileges`, and you can set this permission to a user. Now, when you want to check if the user has a privilege to access admin panel so you can show him an `Admin panel` link, you can do it with:

``` php
@if (Acl::user($userID)->checkGroup('ADMIN_PRIVILEGES'))
    <a href="/admin">Admin Panel</a>    
@endif
```

And when he accesses admin panel, you want to check if he has a permission to manage comments so you can show him a `Comments` link in some menu. You can do it like this:

``` php
@if (Acl::user($userID)->permission('MANAGE_COMMENTS')->check())
    <a href="/admin/comments">Comments</a>
@endif
```

Sorry also for bad documentation, we will improve it ASAP.

**Comment by parrker** [comment]
Thanks for your reply, things are much clearer now! Keep up your good work, it looks like a very nice package!

**Comment by brazorf** [comment]
Hello there,
is there any planned roadmap to allow user roles handling? 
Package looks very good, but i fear the lack of user roles is too much limitating.

**Comment by goranprijic** [comment]
Hey brazorf

We hope that it will be finished until end of the october.
